Repository ReactionMechanismGenerator/RMG-Py, pull requests merged in 2018-02, with the labels that each got.

#1282 Modify O2 special case in MoleculeDrawer
  rmgpy/molecule/draw.py
Labels: PR Easy Review, PR Small

#1275 Corrected modelChemistry in Cantherm species examples
  examples/cantherm/species/C2H4/input.py
  examples/cantherm/species/C2H5/input.py
  examples/cantherm/species/C2H6/input.py
  examples/cantherm/species/H/input.py
Labels: Cantherm, PR Small

#1284 Remove duplicate simulation script
  rmgpy/rmg/main.py
  rmgpy/tools/data/sim/liquid/chem.inp
  rmgpy/tools/data/sim/liquid/input.py
  rmgpy/tools/data/sim/liquid/species_dictionary.txt
  rmgpy/tools/data/sim/simple/chem.inp
  rmgpy/tools/data/sim/simple/input.py
  rmgpy/tools/data/sim/simple/species_dictionary.txt
  rmgpy/tools/simulate.py
  rmgpy/tools/simulateTest.py
  rmgpy/tools/testSensitivity.py
  rmgpy/tools/uncertainty.py
  scripts/simulate.py
  setup.py
Labels: PR Easy Review, PR Ready for Review, PR Small, RMG_scripts, code organization

#1139 print species dictionary with cantherm job
  documentation/source/users/cantherm/output.rst
  rmgpy/cantherm/thermo.py
Labels: Cantherm, PR Ready for Review

#1298 Allow tri-rads in findAllDelocalizationPaths
  rmgpy/molecule/pathfinder.py
Labels: PR Small, Resonance, error

#1260 Hydrogen Bonding
  rmgpy/molecule/group.py
  rmgpy/molecule/molecule.py
  rmgpy/molecule/moleculeTest.py
Labels: PR Ready for Review, PR Small

#1288 fix uncertainty parsing issue
  rmgpy/chemkinTest.py
  rmgpy/data/kinetics/family.py
Labels: PR Ready for Review, PR Small, bugfix
