Repository ReactionMechanismGenerator/RMG-Py, pull requests merged in 2018-06, with the labels that each got.

#1381 Report OpenBabel version in check_dependencies
  utilities.py
Labels: Complexity: Low, Status: Accepted

#1385 Fixed wrong parameter name in kinetics draw
  rmgpy/cantherm/kinetics.py
Labels: Module: Cantherm

#1348 Adding resonance transitons for lone pairs
  rmgpy/chemkin.pyx
  rmgpy/data/base.py
  rmgpy/data/kinetics/common.py
  rmgpy/data/kinetics/depository.py
  rmgpy/data/kinetics/family.py
  rmgpy/data/kinetics/familyTest.py
  rmgpy/data/kinetics/kineticsTest.py
  rmgpy/data/thermo.py
  rmgpy/data/thermoTest.py
  rmgpy/exceptions.py
  rmgpy/molecule/atomtype.py
  rmgpy/molecule/element.py
  rmgpy/molecule/filtration.py
  rmgpy/molecule/filtrationTest.py
  rmgpy/molecule/group.py
  rmgpy/molecule/inchi.py
  rmgpy/molecule/molecule.pxd
  rmgpy/molecule/molecule.py
  rmgpy/molecule/pathfinder.pxd
  rmgpy/molecule/pathfinder.py
  rmgpy/molecule/pathfinderTest.py
  rmgpy/molecule/resonance.pxd
  rmgpy/molecule/resonance.py
  rmgpy/molecule/resonanceTest.py
  rmgpy/molecule/translator.py
  rmgpy/pdep/network.py
  rmgpy/reaction.py
  rmgpy/reactionTest.py
  rmgpy/rmg/model.py
  rmgpy/rmg/modelTest.py
  rmgpy/rmg/react.py
  rmgpy/rmg/rmgTest.py
  rmgpy/species.pxd
  rmgpy/species.py
  rmgpy/speciesTest.py
Labels: Module: Resonance

#1383 Create issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Low, Status: Review Needed

#1374 New recommended families system and improved family loading
  documentation/source/users/rmg/database/images/kinetics_families/1,2_shiftC.png
  documentation/source/users/rmg/database/images/kinetics_families/Intra_R_Add_Exo_scission.png
  documentation/source/users/rmg/database/kinetics.rst
  documentation/source/users/rmg/input.rst
  rmgpy/data/kinetics/database.py
  rmgpy/data/kinetics/kineticsTest.py
  rmgpy/test_data/testing_database/kinetics/families/recommended.py
Labels: Status: Accepted, Type: Feature

#1391 Correct library name parsing in Chemkin readReactionComments()
  rmgpy/chemkin.pyx
Labels: Complexity: Low, Status: Review Needed, Topic: Chemkin, Type: Error

#1395 Automatically skip TCD tests if TCD is unavailable
  Makefile
  rmgpy/data/thermoTest.py
Labels: Complexity: Low, Status: Review Needed, Type: Error

#1396 Update rmgpy.display.display method
  rmgpy/display.py
Labels: Complexity: Low, Status: Review Needed, Type: Bug

#1271 New Flux Diagram Features
  rmgpy/tools/fluxdiagram.py
  rmgpy/tools/fluxtest.py
  scripts/generateFluxDiagram.py
Labels: Status: Review Needed

#1368 Adjust atom sorting algorithm for Molecules
  rmgpy/molecule/molecule.py
  rmgpy/molecule/resonanceTest.py
  rmgpy/molecule/translatorTest.py
Labels: Complexity: Low, Status: Review Needed

#1338 New reaction filtering and trimolecular reactions
  documentation/source/theory/rmg/enlarger.rst
  documentation/source/theory/rmg/fluxAlgorithmWithReactionFiltering.png
  documentation/source/users/rmg/input.rst
  documentation/source/users/rmg/liquids.rst
  examples/rmg/commented/input.py
  rmgpy/data/kinetics/common.py
  rmgpy/data/kinetics/database.py
  rmgpy/data/kinetics/family.py
  rmgpy/data/solvation.py
  rmgpy/kinetics/diffusionLimited.py
  rmgpy/kinetics/diffusionLimitedTest.py
  rmgpy/reaction.pxd
  rmgpy/reaction.py
  rmgpy/restart.py
  rmgpy/rmg/input.py
  rmgpy/rmg/main.py
  rmgpy/rmg/model.py
  rmgpy/rmg/react.py
  rmgpy/rmg/settings.py
  rmgpy/solver/base.pxd
  rmgpy/solver/base.pyx
  rmgpy/solver/liquid.pyx
  rmgpy/solver/simple.pyx
  rmgpy/species.py
  rmgpy/tools/generate_reactions.py
Labels: Status: Review Needed

#1400 Revert "added a work in progress unittest for generatePairs()"
  rmgpy/reactionTest.py
Labels: Complexity: Low, Status: Review Needed, Type: Testing

#1363 Automatic Tree Generation Part 2: Regularization and Speed Up
  ipython/kinetics_library_to_training_tools.py
  rmgpy/data/kinetics/common.py
  rmgpy/data/kinetics/family.py
  rmgpy/data/kinetics/familyTest.py
  rmgpy/molecule/graph.pxd
  rmgpy/molecule/graph.pyx
  rmgpy/molecule/group.pxd
  rmgpy/molecule/group.py
  rmgpy/molecule/groupTest.py
  rmgpy/molecule/molecule.pxd
  rmgpy/molecule/molecule.py
  rmgpy/molecule/vf2.pxd
  rmgpy/molecule/vf2.pyx
  rmgpy/reaction.pxd
  rmgpy/reaction.py
  rmgpy/test_data/testing_database/kinetics/families/Singlet_Carbene_Intra_Disproportionation/groups.py
  rmgpy/test_data/testing_database/kinetics/families/Singlet_Carbene_Intra_Disproportionation/rules.py
  rmgpy/test_data/testing_database/kinetics/families/Singlet_Carbene_Intra_Disproportionation/training/dictionary.txt
  rmgpy/test_data/testing_database/kinetics/families/Singlet_Carbene_Intra_Disproportionation/training/reactions.py
  rmgpy/tools/uncertaintyTest.py
Labels: Complexity: High, Epic, Status: Review Needed, Topic: Kinetics

#1404 Fix critical filterReactions bug
  rmgpy/rmg/main.py
Labels: Emergency, Status: Review Needed

#1405 Handle invalid vector errors gracefully in clar optimization
  rmgpy/molecule/resonance.py
Labels: Module: Resonance, Status: Review Needed, Topic: Aromatics, Type: Error, Type: User Experience

#1408 Fix networkIndices for "edge networks"
  rmgpy/solver/base.pyx
Labels: Complexity: Low, Topic: PDep, Type: Error

#1410 Added a generate_N5dc_radical_resonance_structures resonance transition
  rmgpy/molecule/pathfinder.pxd
  rmgpy/molecule/pathfinder.py
  rmgpy/molecule/pathfinderTest.py
  rmgpy/molecule/resonance.pxd
  rmgpy/molecule/resonance.py
  rmgpy/molecule/resonanceTest.py
Labels: Complexity: Low, Module: Resonance, Topic: Nitrogen, Type: Bug

#1292 Isotope resonance
  documentation/source/users/rmg/modules/index.rst
  documentation/source/users/rmg/modules/isotopes.rst
  rmgpy/constraints.py
  rmgpy/constraintsTest.py
  rmgpy/data/kinetics/family.py
  rmgpy/data/kinetics/familyTest.py
  rmgpy/molecule/isomorphismTest.py
  rmgpy/molecule/molecule.py
  rmgpy/rmg/input.py
  rmgpy/test_data/testing_database/kinetics/families/H_Abstraction/groups.py
  rmgpy/test_data/testing_database/kinetics/families/intra_H_migration/groups.py
  rmgpy/tools/isotopes.py
  rmgpy/tools/isotopesTest.py
  scripts/isotopes.py
Labels: Type: Documentation, Type: Feature

#1339 Peroxide chemistry families
  rmgpy/data/kinetics/family.py
  rmgpy/data/kinetics/groups.py
Labels: Status: Review Needed, Topic: Kinetics, Topic: Liquid, Twin RMG-database PR
