Repository ReactionMechanismGenerator/RMG-Py, pull requests merged in 2018-03, with the labels that each got.

#1303 fix network.__repr__
  rmgpy/pdep/network.py
Labels: PR Ready for Review, PR Small

#1306 Adjust threshold for zero energy in applyInverseLaplaceTransformMethod
  rmgpy/pdep/reaction.pyx
Labels: PR Ready for Review

#1290 Seed mech loading
  rmgpy/data/kinetics/library.py
  rmgpy/exceptions.py
  rmgpy/rmg/input.py
  rmgpy/rmg/main.py
  rmgpy/rmg/mainTest.py
  rmgpy/rmg/model.py
Labels: PR Ready for Review, bugfix

#1310 Added Chlorine `Cl1s` atomType
  documentation/source/reference/molecule/atomtype.rst
  documentation/source/users/rmg/database/introduction.rst
  rmgpy/cantherm/statmech.py
  rmgpy/molecule/atomtype.py
  rmgpy/molecule/atomtypeTest.py
  rmgpy/molecule/element.py
  rmgpy/molecule/group.pxd
  rmgpy/molecule/group.py
  rmgpy/molecule/isomorphismTest.py
  rmgpy/molecule/molecule.pxd
  rmgpy/molecule/molecule.py
  rmgpy/reaction.py
Labels: Chlorine, PR Ready to Merge, Twin RMG-database PR, feature

#1318 Fix sensitivity example
  documentation/source/users/rmg/modules/sensitivity.rst
  examples/sensitivity/run.sh
Labels: PR Easy Review, PR Ready to Merge, PR Small

#1317 Remove reaction duplicate checking at model completion
  rmgpy/rmg/main.py
Labels: Duplicate Reactions, PR Ready for Review

#1321 Adding Iodine as a new reactive element in RMG
  documentation/source/reference/molecule/atomtype.rst
  documentation/source/users/rmg/database/introduction.rst
  rmgpy/molecule/atomtype.py
  rmgpy/molecule/atomtypeTest.py
  rmgpy/molecule/group.pxd
  rmgpy/molecule/group.py
  rmgpy/molecule/isomorphismTest.py
  rmgpy/reaction.py
Labels: Iodine, feature

#1325 Corrected known SMILES in generator.py
  rmgpy/molecule/generator.py
Labels: PR Small

#1276 Update calculateDegeneracy to deal with identical reactants
  rmgpy/data/kinetics/common.py
  rmgpy/data/kinetics/database.py
  rmgpy/data/kinetics/family.py
  rmgpy/data/kinetics/kineticsTest.py
  rmgpy/reaction.py
Labels: PR Ready for Review, PR Small, bugfix

#1262 Refactor translation of molecule identifiers and conversion of molecule formats
  rmgpy/molecule/converter.pxd
  rmgpy/molecule/converter.py
  rmgpy/molecule/converterTest.py
  rmgpy/molecule/generator.py
  rmgpy/molecule/generatorTest.py
  rmgpy/molecule/inchi.pxd
  rmgpy/molecule/inchi.py
  rmgpy/molecule/inchiTest.py
  rmgpy/molecule/inchiparsingTest.py
  rmgpy/molecule/molecule.py
  rmgpy/molecule/moleculeTest.py
  rmgpy/molecule/parser.py
  rmgpy/molecule/parserTest.py
  rmgpy/molecule/resonanceTest.py
  rmgpy/molecule/translator.pxd
  rmgpy/molecule/translator.py
  rmgpy/molecule/translatorTest.py
  rmgpy/qm/molecule.py
  setup.py
Labels: PR Ready for Review, code organization

#1320 Subgraph isomorphism improvements
  rmgpy/molecule/group.pxd
  rmgpy/molecule/group.py
  rmgpy/molecule/groupTest.py
  rmgpy/molecule/molecule.pxd
  rmgpy/molecule/molecule.py
  rmgpy/molecule/moleculeTest.py
  rmgpy/molecule/util.py
Labels: PR Ready for Review, PR Small

#1324 Remove atoms parameter in Cantherm and allow user-defined atomic energies
  documentation/source/users/cantherm/input.rst
  documentation/source/users/cantherm/input_pdep.rst
  examples/cantherm/reactions/23dimethylpropoxy/dimetpropoxy.py
  examples/cantherm/reactions/23dimethylpropoxy/dimetpropoxy_betasci.py
  examples/cantherm/reactions/CH3OH+HCO/ch3oh.py
  examples/cantherm/reactions/CH3OH+HCO/hco.py
  examples/cantherm/reactions/CH3OH+HCO/ts.py
  examples/cantherm/reactions/H+C2H4=C2H5/TS.py
  examples/cantherm/species/Benzyl/benzyl.py
  examples/cantherm/species/C2H4/ethene.py
  examples/cantherm/species/C2H5/ethyl.py
  examples/cantherm/species/C2H6/C2H6.py
  examples/cantherm/species/H/H.py
  examples/cantherm/species/Toulene/toluene_FreeRotor.py
  examples/cantherm/species/Toulene/toluene_HinderedRotor.py
  rmgpy/cantherm/commonTest.py
  rmgpy/cantherm/input.py
  rmgpy/cantherm/statmech.py
Labels: Cantherm, PR Ready for Review

#1332 Raise an error if self.densStates is None
  rmgpy/pdep/configuration.pyx
Labels: Cantherm

#1296 Don't add a PDep reaction to the model if it exists as an unflagged LibraryReaction
  rmgpy/data/kinetics/library.py
  rmgpy/reaction.pxd
  rmgpy/reaction.py
  rmgpy/rmg/pdep.py
Labels: Duplicate Reactions, PR Ready for Review, pDep, risk of error
