Repository ReactionMechanismGenerator/RMG-Py, pull requests merged in 2018-07, with the labels that each got.

#1416 Duplicate fixes
  rmgpy/chemkin.pyx
  rmgpy/chemkinTest.py
  rmgpy/rmg/model.py
Labels: Complexity: Low, Topic: Duplicate Reactions, Type: Bug

#1361 Check core reactions for collision rate limit violators
  rmgpy/reaction.pxd
  rmgpy/reaction.py
  rmgpy/rmg/main.py
Labels: Status: Accepted, Type: Feature

#1423 Corrects a geometry reading error for QChem files
  rmgpy/cantherm/qchem.py
Labels: Complexity: Low, Module: Cantherm

#1429 Add missing trimolecularThreshold
  rmgpy/rmg/main.py
Labels: Complexity: Low, Status: Review Needed

#1432 Adjust updating and resetting of react flags in execute
  rmgpy/rmg/main.py
Labels: Complexity: Low, Emergency, Status: Review Needed, Type: Bug

#1433 Clear vertex mapping after isomorphism
  rmgpy/data/thermoTest.py
  rmgpy/molecule/vf2.pyx
  rmgpy/molecule/vf2Test.py
Labels: Complexity: Low, Status: Review Needed, Type: Bug

#1434 Fix react flag usage in initial react step
  rmgpy/rmg/main.py
  rmgpy/rmg/model.py
  rmgpy/solver/base.pyx
  rmgpy/tools/plot.py
Labels: Complexity: Low, Status: Review Needed, Type: Bug

#1435 Add mpmath to Conda build recipe
  meta.yaml
Labels: Complexity: Low, Status: Review Needed, Type: Environment
