Repository ReactionMechanismGenerator/RMG-Py, pull requests merged in 2018-10, with the labels that each got.

#1481 Omit test files from coverage report
  .coveragerc
Labels: Type: Testing

#1488 Save sensitivity files for all species by specifying 'all'
  rmgpy/rmg/input.py
  rmgpy/rmg/main.py
  rmgpy/tools/loader.py
  rmgpy/tools/simulate.py
Labels: Complexity: Low, Type: Feature

#1484 Clear atom labels from products after reaction generation
  rmgpy/data/kinetics/common.py
  rmgpy/data/kinetics/family.py
Labels: Complexity: Low, Status: Accepted, Type: Bug

#1490 Removed broken link to input file generator form
  documentation/source/users/rmg/input.rst
Labels: Status: Accepted, Type: Documentation

#1487 Symmetry fixes
  rmgpy/molecule/symmetry.pxd
  rmgpy/molecule/symmetry.py
  rmgpy/molecule/symmetryTest.py
  rmgpy/species.py
Labels: Status: Review Needed

#1489 Output a supporting information file in Cantherm
  rmgpy/cantherm/main.py
  rmgpy/cantherm/statmech.py
Labels: Module: Cantherm, Type: Feature

#1473 Miscellaneous Cantherm fixes
  rmgpy/cantherm/common.py
  rmgpy/cantherm/commonTest.py
  rmgpy/cantherm/explorer.py
  rmgpy/cantherm/gaussian.py
  rmgpy/cantherm/input.py
  rmgpy/cantherm/main.py
  rmgpy/cantherm/molpro.py
  rmgpy/cantherm/qchem.py
  rmgpy/reaction.py
  rmgpy/species.py
Labels: Module: Cantherm, Type: Bug

#1478 Travis improvements
  .travis.yml
  deploy.sh
  deploy_key.enc
  documentation/Makefile
Labels: Complexity: Low, Status: Review Needed

#1467 Fix Uncertainty after RangedReactor refactoring
  rmgpy/solver/liquid.pyx
  rmgpy/solver/simple.pyx
  rmgpy/tools/uncertainty.py
Labels: Complexity: Low, Module: Scripts, Status: Accepted, Type: Bug

#1497 Fix: rotationalConstant supporting info
  rmgpy/cantherm/main.py
Labels: Module: Cantherm, Type: Bug
