Repository ReactionMechanismGenerator/RMG-Py, pull requests merged in 2018-05, with the labels that each got.

#1146 Canthermchanges2
  documentation/source/users/cantherm/input.rst
  rmgpy/cantherm/data/HOSI_ccsd_t1.out
  rmgpy/cantherm/gaussian.py
  rmgpy/cantherm/gaussianTest.py
  rmgpy/cantherm/molpro.py
  rmgpy/cantherm/molproTest.py
  rmgpy/cantherm/qchem.py
  rmgpy/cantherm/qchemTest.py
  rmgpy/cantherm/statmech.py
Labels: Cantherm

#1270 Add ring attribute to atoms
  rmgpy/data/kinetics/family.py
  rmgpy/molecule/adjlist.py
  rmgpy/molecule/adjlistTest.py
  rmgpy/molecule/converter.py
  rmgpy/molecule/group.pxd
  rmgpy/molecule/group.py
  rmgpy/molecule/molecule.pxd
  rmgpy/molecule/molecule.py
  rmgpy/molecule/moleculeTest.py
Labels: PR Ready for Review

#1365 Merge v2.1.9 updates and new git workflow
  bld.bat
  build.sh
  documentation/source/users/rmg/releaseNotes.rst
  meta.yaml
  rmgpy/version.py
  setup.py
Labels: PR Ready for Review, PR Small

#1357 Allow PDep reactions and non-template library reactions in PDep networks
  documentation/source/users/rmg/database/modification.rst
  rmgpy/cantherm/pdep.py
  rmgpy/data/kinetics/common.py
  rmgpy/data/kinetics/library.py
  rmgpy/data/kinetics/libraryTest.py
  rmgpy/pdep/collision.pyx
  rmgpy/pdep/network.py
  rmgpy/pdep/reaction.pyx
  rmgpy/reaction.pxd
  rmgpy/reaction.py
  rmgpy/rmg/model.py
  rmgpy/rmg/pdep.py
  rmgpy/test_data/testing_database/kinetics/libraries/lib_net/dictionary.txt
  rmgpy/test_data/testing_database/kinetics/libraries/lib_net/reactions.py
Labels: PR Ready for Review, pDep

#1364 Various Cantherm UX improvements
  documentation/source/users/cantherm/input.rst
  documentation/source/users/cantherm/input_pdep.rst
  examples/cantherm/networks/methoxy/README.txt
  examples/cantherm/networks/methoxy/input.py
  examples/cantherm/networks/methoxy/run-cantherm
  examples/cantherm/reactions/23dimethylpropoxy/cantherm_dimetpropoxy.py
  examples/cantherm/reactions/23dimethylpropoxy/dimetpropoxy.py
  examples/cantherm/reactions/23dimethylpropoxy/dimetpropoxy_betasci.py
  examples/cantherm/reactions/CH3OH+HCO/ch3oh.py
  examples/cantherm/reactions/CH3OH+HCO/hco.py
  examples/cantherm/reactions/CH3OH+HCO/input.py
  examples/cantherm/reactions/CH3OH+HCO/ts.py
  examples/cantherm/reactions/H+C2H4=C2H5/TS.py
  examples/cantherm/species/Benzyl/benzyl.py
  examples/cantherm/species/Benzyl/input.py
  examples/cantherm/species/C2H4/ethene.py
  examples/cantherm/species/C2H4/input.py
  examples/cantherm/species/C2H5/ethyl.py
  examples/cantherm/species/C2H5/input.py
  examples/cantherm/species/C2H6/C2H6.py
  examples/cantherm/species/C2H6/input.py
  examples/cantherm/species/H/H.py
  examples/cantherm/species/H/input.py
  examples/cantherm/species/Toulene/input_toluene_FreeRotor.py
  examples/cantherm/species/Toulene/input_toluene_HinderedRotor.py
  examples/cantherm/species/Toulene/toluene_FreeRotor.py
  examples/cantherm/species/Toulene/toluene_HinderedRotor.py
  rmgpy/cantherm/gaussian.py
  rmgpy/cantherm/input.py
  rmgpy/cantherm/kinetics.py
  rmgpy/cantherm/main.py
  rmgpy/cantherm/molpro.py
  rmgpy/cantherm/pdep.py
  rmgpy/cantherm/qchem.py
  rmgpy/cantherm/statmech.py
  rmgpy/cantherm/thermo.py
  rmgpy/pdep/configuration.pyx
  rmgpy/pdep/reaction.pyx
  rmgpy/rmg/pdep.py
Labels: Cantherm

#1369 Characteristic Rate Based Termination Criterion
  documentation/source/users/rmg/input.rst
  rmgpy/rmg/input.py
  rmgpy/rmg/test_data/mainTest/input.py
  rmgpy/solver/base.pyx
Labels: PR Ready for Review, PR Small, feature

#1356 Newest version of debug_CO
  rmgpy/data/kinetics/family.py
  rmgpy/data/kinetics/familyTest.py
  rmgpy/molecule/atomtype.py
  rmgpy/molecule/group.pxd
  rmgpy/molecule/group.py
  rmgpy/test_data/testing_database/kinetics/families/R_Addition_COm/groups.py
  rmgpy/test_data/testing_database/kinetics/families/R_Addition_COm/rules.py
  rmgpy/test_data/testing_database/kinetics/families/R_Addition_COm/training/dictionary.txt
  rmgpy/test_data/testing_database/kinetics/families/R_Addition_COm/training/reactions.py
Labels: Twin RMG-database PR

#1359 Fix matchNodeToChild to account for ancestor comparison
  rmgpy/data/base.py
Labels: PR Ready for Review, PR Small

#1371 Allow Resurrection from Failed Filter Simulations
  rmgpy/rmg/main.py
Labels: PR Ready for Review, PR Small

#1217 Do not consider template differences from resonance structures as multiple TS
  rmgpy/data/kinetics/common.py
  rmgpy/data/kinetics/family.py
  rmgpy/data/kinetics/kineticsTest.py
  rmgpy/rmg/model.py
  rmgpy/rmg/modelTest.py
  rmgpy/rmg/rmgTest.py
  rmgpy/test_data/testing_database/kinetics/families/H_Abstraction/groups.py
Labels: Duplicate Reactions, PR Ready for Review, Speed-up, bugfix

#1373 Revamped training reaction ipython notebook
  ipython/kinetics_library_to_training.ipynb
  ipython/kinetics_library_to_training_tools.py
  rmgpy/data/kinetics/family.py
Labels: PR Ready for Review

#1376 Added sensitivity analysis to Cantherm
  cantherm.py
  documentation/source/users/cantherm/input.rst
  documentation/source/users/cantherm/input_pdep.rst
  examples/cantherm/networks/acetyl+O2/input.py
  rmgpy/cantherm/input.py
  rmgpy/cantherm/kinetics.py
  rmgpy/cantherm/pdep.py
  rmgpy/cantherm/pdepTest.py
  rmgpy/cantherm/sensitivity.py
  rmgpy/cantherm/thermo.py
  rmgpy/test_data/Cantherm/tst1/pdep_sa.py
Labels: Cantherm, PR Ready to Merge, feature
