Repository ReactionMechanismGenerator/RMG-Py, pull requests merged in 2019-12, with the labels that each got.

#1636 Fix bugs in Chemkin thermo entry element reading/writing
  rmgpy/chemkin.pyx
  rmgpy/chemkinTest.py
  rmgpy/molecule/molecule.py
Labels: For Next Release, Status: Discussion Needed, Topic: Chemkin, Type: Bug

#1832 fixed the solvation GAV heuristic
  rmgpy/data/solvation.py
  rmgpy/data/solvationTest.py
Labels: Complexity: Low, For Next Release

#1836 Add isotopes script to package
  setup.py
Labels: For Next Release

#1825 Added Iodine as element in Chemkin input file
  rmgpy/chemkin.pyx
Labels: Complexity: Low, For Next Release, Topic: Chemkin, Type: Error

#1834 Enable fitting and reversing of negative reaction rates.
  rmgpy/kinetics/arrhenius.pyx
  rmgpy/kinetics/arrheniusTest.py
Labels: For Next Release, Status: Ready for Review

#1842 Collection of small fixes
  .conda/meta.yaml
  arkane/pdepTest.py
  environment.yml
  rmgpy/chemkin.pyx
  rmgpy/chemkinTest.py
  rmgpy/constraintsTest.py
  rmgpy/data/kinetics/family.py
  rmgpy/data/kinetics/familyTest.py
  rmgpy/data/thermoTest.py
  rmgpy/data/transportTest.py
  rmgpy/kinetics/arrhenius.pyx
  rmgpy/molecule/converter.py
  rmgpy/molecule/translator.py
  rmgpy/molecule/translatorTest.py
  rmgpy/rmg/rmgTest.py
  rmgpy/thermo/thermoengine.py
  scripts/rmg2to3.py
Labels: Complexity: Low, For Next Release, Good First Issue

#1809 Allow mole fractions to be normalized if they do not sum to one
  rmgpy/rmg/input.py
  rmgpy/rmg/inputTest.py
Labels: Complexity: Low, For Next Release, Good First Issue

#1738 Update global uncertainty module to work with MUQ 2
  documentation/source/users/rmg/input.rst
  environment.yml
  ipython/data/pdd_model/chem_annotated.inp
  ipython/data/pdd_model/input.py
  ipython/data/pdd_model/species_dictionary.txt
  ipython/global_uncertainty.ipynb
  rmgpy/rmg/input.py
  rmgpy/rmg/main.py
  rmgpy/tools/globaluncertainty.py
  rmgpy/tools/muq.py
Labels: Complexity: Medium, For Next Release

#1796 Fix WSL permisson bug for renaming directories
  rmgpy/rmg/main.py
Labels: Complexity: Low, For Next Release, Platform: Windows, Status: Ready for Review, Type: Bug

#1847 Restart attribute error
  rmgpy/rmg/main.py
  rmgpy/rmg/mainTest.py
  rmgpy/rmg/test_data/restartTest/restart_no_filters.py
  rmgpy/rmg/test_data/restartTest/restart_w_filters.py
  rmgpy/rmg/test_data/restartTest/seed_no_filters/filters/filters.h5
  rmgpy/rmg/test_data/restartTest/seed_no_filters/filters/species_map.yml
  rmgpy/rmg/test_data/restartTest/seed_no_filters/seed/dictionary.txt
  rmgpy/rmg/test_data/restartTest/seed_no_filters/seed/reactions.py
  rmgpy/rmg/test_data/restartTest/seed_no_filters/seed_edge/dictionary.txt
  rmgpy/rmg/test_data/restartTest/seed_no_filters/seed_edge/reactions.py
  rmgpy/rmg/test_data/restartTest/seed_w_filters/filters/filters.h5
  rmgpy/rmg/test_data/restartTest/seed_w_filters/filters/species_map.yml
  rmgpy/rmg/test_data/restartTest/seed_w_filters/seed/dictionary.txt
  rmgpy/rmg/test_data/restartTest/seed_w_filters/seed/reactions.py
  rmgpy/rmg/test_data/restartTest/seed_w_filters/seed_edge/dictionary.txt
  rmgpy/rmg/test_data/restartTest/seed_w_filters/seed_edge/reactions.py
Labels: Complexity: Low, For Next Release, Status: Ready for Review, Topic: Restart, Type: Bug

#1849 ND Hindered Rotor Improvements
  arkane/input.py
  examples/arkane/species/Toulene_Hindered_Rotor_SemiClassicalND/toluene_HinderedRotor.py
  rmgpy/statmech/conformer.pyx
  rmgpy/statmech/ndTorsions.py
  rmgpy/statmech/ndTorsionsTest.py
Labels: Arkane, Complexity: Medium, Status: Ready for Review, Topic: Performance, Type: Bug
