Repository ReactionMechanismGenerator/RMG-Py, pull requests merged in 2019-02, with the labels that each got.

#1546 Move variable initiation to avoid undefined variable error
  rmgpy/rmg/model.py
Labels: Complexity: Low, Status: Review Needed, Type: Bug

#1542 Non-cat changes to master from cat branch, 2
  documentation/source/users/rmg/output.rst
  documentation/source/users/rmg/releaseNotes.rst
  rmgpy/data/kinetics/database.py
  rmgpy/data/kinetics/family.py
  rmgpy/molecule/adjlist.py
  rmgpy/molecule/atomtype.pxd
  rmgpy/molecule/atomtype.py
  rmgpy/molecule/atomtypeTest.py
  rmgpy/molecule/atomtypedatabase.py
  rmgpy/molecule/converter.py
  rmgpy/molecule/draw.py
  rmgpy/molecule/group.pxd
  rmgpy/molecule/group.py
  rmgpy/molecule/groupTest.py
  rmgpy/molecule/molecule.pxd
  rmgpy/molecule/molecule.py
  rmgpy/molecule/moleculeTest.py
  rmgpy/rmg/listener.py
  rmgpy/solver/base.pyx
Labels: Status: Review Needed

#1552 Allow RDKit to ignore hydrogen bonds
  rmgpy/molecule/converter.py
  rmgpy/molecule/converterTest.py
Labels: Complexity: Low, Status: Review Needed

#1556 Properly remove forbidden species from edge
  rmgpy/rmg/model.py
Labels: Complexity: Low, Emergency, Status: Review Needed, Type: Bug, Type: Risk of Error
