Repository ReactionMechanismGenerator/RMG-Py, pull requests merged in 2019-09, with the labels that each got.

#1717 Move parse_command_line_arguments to util.py
  rmg.py
  rmgpy/rmg/rmgTest.py
  rmgpy/tools/generate_reactions.py
  rmgpy/util.py
Labels: Complexity: Low, Status: Review Needed, Topic: Installation, Type: Bug

#1685 Allow relative paths in Arkane statmech
  arkane/commonTest.py
  arkane/data/H2O2/freq_a19031.out
  arkane/data/H2O2/scan_a19034.out
  arkane/data/H2O2/sp_a19032.out
  arkane/explorerTest.py
  arkane/gaussianTest.py
  arkane/inputTest.py
  arkane/kineticsTest.py
  arkane/mainTest.py
  arkane/molproTest.py
  arkane/pdepTest.py
  arkane/qchemTest.py
  arkane/statmech.py
  arkane/statmechTest.py
  arkane/thermoTest.py
Labels: Arkane, Type: Bug

#1721 Reduce the amount of logging messages that get too frequently printed during debug
  rmgpy/constraints.py
  rmgpy/data/base.py
  rmgpy/data/kinetics/common.py
  rmgpy/data/kinetics/family.py
  rmgpy/data/kinetics/groups.py
  rmgpy/data/thermo.py
Labels: Complexity: Low

#1731 Improve group additivity ranking for aromatic species
  rmgpy/data/thermo.py
  rmgpy/data/thermoTest.py
  rmgpy/molecule/molecule.pxd
  rmgpy/molecule/molecule.py
  rmgpy/molecule/moleculeTest.py
Labels: Complexity: Low, Topic: Thermo

#1729 Remove unnecessary zip folder unpacking in arkane/mainTest.py
  arkane/mainTest.py
Labels: Complexity: Low
