Repository ReactionMechanismGenerator/RMG-Py, pull requests merged in 2019-10, with the labels that each got.

#1741 Fix inconsistent molecule fingerprint generation
  rmgpy/molecule/molecule.py
  rmgpy/molecule/moleculeTest.py
Labels: Complexity: Low, Type: Bug

#1737 Do not force change matplotlib backend in tools.plot
  rmgpy/tools/plot.py
Labels: Complexity: Low, Type: Bug

#1752 Fix two calls to Exception.message, which no longer exists
  rmgpy/chemkin.pyx
  rmgpy/solver/base.pyx
Labels: Complexity: Low, Type: Bug

#1751 Dms oxy changes
  rmgpy/data/thermo.py
  rmgpy/data/thermoTest.py
  rmgpy/molecule/filtration.py
  rmgpy/molecule/filtrationTest.py
  rmgpy/molecule/molecule.py
  rmgpy/molecule/pathfinder.py
  rmgpy/molecule/resonanceTest.py
  rmgpy/rmg/input.py
  rmgpy/solver/mbSampled.pyx
  rmgpy/solver/simple.pyx
  rmgpy/tools/simulate.py
Labels: Topic: Sulfur, Topic: Thermo, Twin RMG-database PR

#1756 Fix conda build issues
  .conda/meta.yaml
  Makefile
  rmg.py
Labels: Complexity: Low, Py3, Status: Review Needed

#1755 Reduced print statement frequency for exceeded max number of objects.…
  rmgpy/solver/base.pyx
Labels: Complexity: Low, Good First Issue, Module: Cython, Module: Logging

#1763 Removing RMG job scheduler instructions and updating RMG-parallel run…
  documentation/source/users/rmg/running.rst
Labels: Topic: Parallel, Type: Documentation

#1734 Add thermo library list to rmgpy/data/thermoTest.py
  rmgpy/data/thermoTest.py
Labels: Complexity: Low, Status: Review Needed, Type: Testing

#1765 Performance improvements to pdep logging
  rmgpy/pdep/network.py
  rmgpy/pdep/reaction.pyx
Labels: Module: Logging, Topic: Performance

#1735 Update IPython notebooks
  ipython/cantera_sensitivity_comparison.ipynb
  ipython/cantera_simulation.ipynb
  ipython/combustion_model_and_ignition_delay_demo.ipynb
  ipython/data/parse_source/chem_annotated.inp
  ipython/data/parse_source/species_dictionary.txt
  ipython/findParameterSourcesAndAssignUncertainies.ipynb
  ipython/find_parameter_sources_and_assign_uncertainties.ipynb
  ipython/generateReactions.ipynb
  ipython/generate_reactions.ipynb
  ipython/kinetics_library_to_training.ipynb
  ipython/kinetics_library_to_training_tools.py
  ipython/local_uncertainty.ipynb
  ipython/mechanism_analyzer.ipynb
  ipython/regression_test.ipynb
  rmgpy/data/kinetics/family.py
  rmgpy/data/kinetics/familyTest.py
  rmgpy/data/kinetics/rules.py
  rmgpy/molecule/draw.py
  rmgpy/molecule/translator.py
Labels: Status: Ready for Review

#1767 Update documentation from py2 to py3
  .travis.yml
  documentation/source/_static/custom.css
  documentation/source/reference/arkane/index.rst
  documentation/source/reference/arkane/input.rst
  documentation/source/reference/chemkin/index.rst
  documentation/source/reference/chemkin/reader.rst
  documentation/source/reference/chemkin/writer.rst
  documentation/source/reference/data/index.rst
  documentation/source/reference/data/logicnode.rst
  documentation/source/reference/data/statmechfit.rst
  documentation/source/reference/molecule/adjlist.rst
  documentation/source/reference/molecule/atomtype.rst
  documentation/source/reference/molecule/element.rst
  documentation/source/reference/molecule/index.rst
  documentation/source/reference/molecule/symmetry.rst
  documentation/source/reference/pdep/index.rst
  documentation/source/reference/pdep/mastereqn.rst
  documentation/source/reference/pdep/methods.rst
  documentation/source/reference/pdep/reaction.rst
  documentation/source/reference/rmg/index.rst
  documentation/source/reference/rmg/input.rst
  documentation/source/reference/rmg/main.rst
  documentation/source/reference/rmg/output.rst
  documentation/source/reference/statmech/index.rst
  documentation/source/users/arkane/input.rst
  documentation/source/users/rmg/installation/anacondaDeveloper.rst
  documentation/source/users/rmg/installation/anacondaUser.rst
  documentation/source/users/rmg/installation/index.rst
  documentation/source/users/rmg/installation/linuxSubsystem.rst
  documentation/source/users/rmg/installation/virtualMachineSetup.rst
  documentation/source/users/rmg/modules/databaseScripts.rst
  rmgpy/data/kinetics/__init__.py
  rmgpy/data/statmechfit.py
  rmgpy/molecule/__init__.py
  rmgpy/molecule/atomtype.py
  rmgpy/molecule/element.py
Labels: Complexity: Low, Type: Documentation

#1769 Output RMG libraries in Arkane
  arkane/input.py
  arkane/inputTest.py
  arkane/main.py
  arkane/output.py
  arkane/outputTest.py
Labels: Arkane, Type: Feature

#1785 Several small Pdep bug fixes
  arkane/common.py
  rmgpy/pdep/me.pyx
  rmgpy/pdep/network.py
Labels: Topic: PDep, Type: Bug

#1758 Add atom index to Group()._repr_png_
  rmgpy/molecule/group.py
  rmgpy/molecule/groupTest.py
Labels: Complexity: Low
