Repository ReactionMechanismGenerator/RMG-Py, pull requests merged in 2020-11, with the labels that each got.

#2035 Improve debugging error messages
  rmgpy/data/kinetics/database.py
  rmgpy/data/thermo.py
  rmgpy/data/thermoTest.py
  rmgpy/rmg/input.py
  rmgpy/rmg/model.py
Labels: Status: Ready for Review

#1945 Reference concentration for surface species when calculating Kc
  rmgpy/reaction.pxd
  rmgpy/reaction.py
  rmgpy/reactionTest.py
Labels: Status: Ready for Review, Topic: Catalysis, Topic: Thermo

#2044 Fix format specifier when logging species pruning.
  rmgpy/rmg/model.py
Labels: Complexity: Low, Priority: High, Status: Accepted, Status: Ready for Review, Topic: Pruning, Type: Bug

#2017 Correct surfaceThermoPt111 library name in examples and documentation.
  documentation/source/users/rmg/surfaces.rst
  examples/rmg/catalysis/ch4_o2/input.py
  examples/rmg/catalysis/methane_steam/input.py
  rmgpy/data/thermo.py
Labels: Status: Accepted, Status: Ready for Review, Topic: Catalysis
