Repository ReactionMechanismGenerator/RMG-Py, pull requests merged in 2020-03, with the labels that each got.

#1855 Minor changes in treating collision rate violating reactions:
  rmgpy/chemkin.pyx
  rmgpy/rmg/main.py
Labels: Complexity: Low

#1900 Adding in a new database test to check all surface training reactions are useable
  rmgpy/data/kinetics/family.py
  testing/databaseTest.py
Labels: Complexity: Low, Status: Ready for Review

#1861 T3 related modifications
  arkane/sensitivity.py
  rmgpy/rmg/input.py
  rmgpy/rmg/main.py
Labels: T3
