Repository ReactionMechanismGenerator/RMG-Py, pull requests merged in 2020-08, with the labels that each got.

#1994 Modify Pmin/Pmax code in main.py & Feed in species_list for ThirdBody type kinetics to allow collision limit violation check
  rmgpy/rmg/main.py
Labels: Complexity: Low, Status: Ready for Review

#1996 Updated catalystProperties in catalysis example input files
  examples/rmg/catalysis/ch4_o2/input.py
  examples/rmg/catalysis/methane_steam/input.py
Labels: Topic: Catalysis

#1952 Debugged global uncertainty analysis
  rmgpy/rmg/input.py
  rmgpy/rmg/main.py
Labels: Complexity: Low, Status: Ready for Review

#1949 Unit fix for reverse rate constants with surface species
  rmgpy/kinetics/model.pxd
  rmgpy/kinetics/model.pyx
  rmgpy/reaction.py
  rmgpy/reactionTest.py
Labels: Status: Ready for Review, Topic: Catalysis

#2007 Avoid accessibility test for Retroene family
  testing/databaseTest.py
Labels: Complexity: Low, For Next Release, Status: Ready for Review, Twin RMG-database PR

#1894 Find and fix a bug in Molecule isomorphism
  rmgpy/molecule/isomorphismTest.py
  rmgpy/molecule/molecule.py
Labels: Complexity: Low, Type: Bug

#1978 Used fsolve for BM if only 1 training reaction
  rmgpy/data/kinetics/family.py
  rmgpy/kinetics/arrhenius.pyx
Labels: Complexity: Low, Status: Ready for Review

#2006 Fixes to adsorption thermochemistry estimation, including bidentate.
  rmgpy/data/thermo.py
  rmgpy/data/thermoTest.py
  rmgpy/molecule/molecule.py
Labels: Topic: Catalysis

#1925 Read all Chebyshev coefficients from Chemkin files
  rmgpy/chemkin.pyx
Labels: Status: Ready for Review

#1907 Adding new surface attributes
  rmgpy/data/base.py
  rmgpy/data/kinetics/depository.py
  rmgpy/data/kinetics/family.py
  rmgpy/data/kinetics/library.py
  rmgpy/data/test_data/thermo/groups/adsorptionPt111.py
  rmgpy/data/thermo.py
  rmgpy/test_data/testing_database/thermo/groups/adsorptionPt111.py
  testing/databaseTest.py
Labels: Status: Ready for Review, Topic: Catalysis, Twin RMG-database PR

#1982 Minor: Remove unicode encoding & use f-string in reference
  rmgpy/data/reference.py
Labels: Complexity: Low, Status: Ready for Review
