Repository ReactionMechanismGenerator/RMG-Py, pull requests merged in 2020-05, with the labels that each got.

#1870 Move Arkane Data to RMG-database
  arkane/encorr/corr.py
  arkane/encorr/data.py
  arkane/input.py
  arkane/statmech.py
Labels: Arkane, Complexity: Low, Twin RMG-database PR, Type: Code Organization

#1910 Added an option to save atom order when adding atom labels for a template reaction
  rmgpy/data/kinetics/family.py
  rmgpy/molecule/molecule.py
  rmgpy/reaction.pxd
  rmgpy/reaction.py
  rmgpy/reactionTest.py
  rmgpy/species.pxd
  rmgpy/species.py
Labels: Topic: ARC, Type: Feature

#1918 Debugged liquid phase range based reactor
  rmgpy/rmg/main.py
Labels: Complexity: Low, Status: Ready for Review, Topic: Liquid, Type: Bug

#1920 BAC fitting in Arkane
  arkane/encorr/bac.py
  arkane/encorr/bacTest.py
  arkane/encorr/corr.py
  arkane/encorr/data.py
  arkane/encorr/dataTest.py
  arkane/encorr/decomp.py
  arkane/encorr/decompTest.py
  arkane/encorr/mbac.py
  arkane/encorr/pbac.py
  arkane/encorr/reference.py
  arkane/input.py
  arkane/main.py
  arkane/mainTest.py
  documentation/source/users/arkane/input.rst
  examples/arkane/bac/wb97m-v_def2-tzvpd/input.py
Labels: Complexity: Medium, Status: Ready for Review

#1939 Minor: Updated files in /ipython/data/parse_source
  ipython/data/parse_source/chem_annotated.inp
  ipython/data/parse_source/species_dictionary.txt
Labels: Complexity: Low, Status: Ready for Review

#1927 Feature: Allow easy choice between two- and three- parameter Arrhenius fit in Arkane
  arkane/common.py
  arkane/input.py
  arkane/kinetics.py
  arkane/mainTest.py
  documentation/source/users/arkane/input.rst
  testing/arkane/two_parameter_arrhenius_fit/CH3OO.py
  testing/arkane/two_parameter_arrhenius_fit/CH3OOH.py
  testing/arkane/two_parameter_arrhenius_fit/TS.py
  testing/arkane/two_parameter_arrhenius_fit/ch3oo_freq.log
  testing/arkane/two_parameter_arrhenius_fit/ch3oo_sp.log
  testing/arkane/two_parameter_arrhenius_fit/ch3ooh_freq.log
  testing/arkane/two_parameter_arrhenius_fit/ch3ooh_sp.log
  testing/arkane/two_parameter_arrhenius_fit/imipramine.py
  testing/arkane/two_parameter_arrhenius_fit/imipramine_freq.log
  testing/arkane/two_parameter_arrhenius_fit/imipramine_sp.log
  testing/arkane/two_parameter_arrhenius_fit/imipraminerad.py
  testing/arkane/two_parameter_arrhenius_fit/imipraminerad_freq.out
  testing/arkane/two_parameter_arrhenius_fit/imipraminerad_sp.out
  testing/arkane/two_parameter_arrhenius_fit/input.py
  testing/arkane/two_parameter_arrhenius_fit/ts_freq.out
  testing/arkane/two_parameter_arrhenius_fit/ts_sp.out
Labels: Arkane, Complexity: Low, Priority: High, Topic: ARC, Topic: Kinetics, Type: Feature

#1947 BugFix: correct AtomTypeError
  rmgpy/molecule/atomtype.py
Labels: Complexity: Low, Module: Molecule, Status: Ready for Review, Type: Bug

#1944 Modified find_parameter_sources_and_assign_uncertainties to regenerate chem.inp
  ipython/data/parse_source/chem_annotated.inp
  ipython/data/parse_source/species_dictionary.txt
  ipython/find_parameter_sources_and_assign_uncertainties.ipynb
Labels: Complexity: Low, Module: Scripts, Status: Ready for Review

#1948 Minor: add solvation correction in species.thermo.comment
  rmgpy/data/solvation.py
  rmgpy/thermo/thermoengine.py
Labels: Complexity: Low, Status: Ready for Review, Topic: Liquid

#1926 Fix labels of missing thermo groups
  rmgpy/data/thermo.py
Labels: T3

#1951 BAC options
  arkane/encorr/bac.py
  arkane/encorr/data.py
  arkane/encorr/dataTest.py
  arkane/input.py
  documentation/source/users/arkane/input.rst
Labels: Arkane, Status: Ready for Review

#1950 Atom energy fitting
  arkane/encorr/ae.py
  arkane/encorr/aeTest.py
  arkane/encorr/bac.py
  arkane/encorr/reference.py
  arkane/input.py
  arkane/main.py
  documentation/source/users/arkane/input.rst
Labels: Arkane, Status: Ready for Review, Twin RMG-database PR

#1940 Standardize model chemistry
  arkane/common.py
  arkane/commonTest.py
  arkane/data/species/reference_species_example.yml
  arkane/encorr/ae.py
  arkane/encorr/aeTest.py
  arkane/encorr/bac.py
  arkane/encorr/bacTest.py
  arkane/encorr/corr.py
  arkane/encorr/data.py
  arkane/encorr/dataTest.py
  arkane/encorr/isodesmic.py
  arkane/encorr/isodesmicTest.py
  arkane/encorr/reference.py
  arkane/encorr/referenceTest.py
  arkane/ess/adapter.py
  arkane/input.py
  arkane/inputTest.py
  arkane/main.py
  arkane/modelchem.py
  arkane/modelchemTest.py
  arkane/statmech.py
  arkane/statmechTest.py
  documentation/source/users/arkane/input.rst
  examples/arkane/bac/wb97m-v_def2-tzvpd/input.py
  examples/arkane/species/Pentyl_isodesmic/input.py
  rmgpy/rmgobject.pyx
  rmgpy/rmgobjectTest.py
Labels: Arkane, Status: Ready for Review, Twin RMG-database PR

#1958 Allow atom energy fitting if not all species are provided
  arkane/encorr/ae.py
Labels: Arkane, Complexity: Low, Priority: High, Status: Ready for Review

#1962 Avoid SMILES translation errors for reference species
  arkane/encorr/reference.py
Labels: Complexity: Low, Status: Ready for Review, Twin RMG-database PR, Type: Bug
