Repository ReactionMechanismGenerator/RMG-Py, pull requests merged in 2021-04, with the labels that each got.

#2095 Documentation: Inclusion of diverse Linux distributions
  .gitignore
  documentation/source/users/rmg/installation/anacondaDeveloper.rst
Labels: Topic: Installation

#2097 Changed call for rmgpy.tools.generate_reactions to rmgpy.tools.generatere…
  ipython/generate_reactions.ipynb
Labels: Jupyter notebook

#2073 Create docs.yml
  .github/workflows/docs.yml
  .travis.yml
  documentation/Makefile
Labels: Status: Ready for Review

#2091 Switch to newer cclib?
  environment.yml
  rmgpy/qm/molecule.py
  rmgpy/qm/mopac.py
  rmgpy/qm/qmdata.py
Labels: Complexity: Low, For Next Release, Module: QM, Priority: High, Status: Ready for Review, Type: Bug

#2066 Updated the amu values of common elements in gas phase chemistry
  rmgpy/molecule/element.py
Labels: Arkane, Complexity: Low, Type: Error

#2088 Switch to OpenBabel 3
  arkane/encorr/bacTest.py
  arkane/encorr/data.py
  arkane/encorr/dataTest.py
  documentation/source/users/rmg/species.rst
  environment.yml
  rmgpy/molecule/converter.pxd
  rmgpy/molecule/converter.py
  rmgpy/molecule/pathfinderTest.py
  rmgpy/molecule/translator.py
  rmgpy/molecule/translatorTest.py
  utilities.py
Labels: Twin RMG-ARC PR, Type: Environment

#2108 Better Github Actions workflow for dual Py/Database updates.
  .github/workflows/CI.yml
  trigger-rmg-tests.sh
Labels: Status: Ready for Review

#2105 Only calculate Peff for a specific collider if [collider] is known
  rmgpy/solver/files/specific_collider_model/chem.inp
  rmgpy/solver/files/specific_collider_model/species_dictionary.txt
  rmgpy/solver/simple.pyx
  rmgpy/solver/simpleTest.py
Labels: Topic: Kinetics, Type: Bug

#1997 halogen additions (simultaneous update with DB)
  documentation/source/reference/molecule/atomtype.rst
  rmgpy/data/base.py
  rmgpy/data/thermo.py
  rmgpy/molecule/atomtype.py
  rmgpy/molecule/group.py
  rmgpy/molecule/molecule.pxd
  rmgpy/molecule/molecule.py
  rmgpy/molecule/moleculeTest.py
  rmgpy/molecule/translator.py
  rmgpy/molecule/translatorTest.py
  testing/databaseTest.py
Labels: Status: Ready for Review
