Repository ReactionMechanismGenerator/RMG-Py, pull requests merged in 2021-07, with the labels that each got.

#2173 Forming surface bonds
  rmgpy/data/kinetics/family.py
  rmgpy/molecule/group.pxd
  rmgpy/molecule/group.py
  rmgpy/molecule/molecule.pxd
  rmgpy/molecule/molecule.py
Labels: Status: WIP, Topic: Catalysis

#2168 Some miscellaneous fixes
  rmgpy/reactionTest.py
  rmgpy/rmg/model.py
  rmgpy/solver/base.pxd
  rmgpy/solver/liquid.pyx
  rmgpy/solver/mbSampled.pyx
  rmgpy/solver/simple.pyx
  rmgpy/solver/surface.pyx
  rmgpy/solver/surfaceTest.py
Labels: Complexity: Low, Status: Ready for Review

#2174 Minor change to `get_all_solute_data` function.
  ipython/estimate_solvation_thermo_and_search_available_solvents.ipynb
  ipython/temperature_dependent_solvation_free_energy.ipynb
  rmgpy/data/solvation.py
  rmgpy/data/solvationTest.py
Labels: Complexity: Low

#2181 Load chemkin bug fix - extended elements and digits
  rmgpy/chemkin.pyx
Labels: Complexity: Low, Topic: Chemkin, Type: Bug

#2182 Added additional features to preserve atom order and template labels when generating reactions
  rmgpy/data/kinetics/family.py
  rmgpy/data/kinetics/familyTest.py
  rmgpy/molecule/filtration.py
  rmgpy/molecule/resonance.py
  rmgpy/reaction.py
Labels: Topic: ARC

#2090 Adding in coverage dependent effects to surface kinetics
  documentation/source/users/rmg/surfaces.rst
  rmgpy/chemkin.pyx
  rmgpy/chemkinTest.py
  rmgpy/data/kinetics/family.py
  rmgpy/data/kinetics/library.py
  rmgpy/kinetics/surface.pxd
  rmgpy/kinetics/surface.pyx
  rmgpy/kinetics/surfaceTest.py
  rmgpy/reactionTest.py
  rmgpy/rmg/input.py
  rmgpy/rmg/main.py
  rmgpy/rmg/model.py
  rmgpy/solver/surface.pyx
  rmgpy/solver/surfaceTest.py
  rmgpy/test_data/testing_database/kinetics/libraries/surface-example/reactions.py
  testing/databaseTest.py
Labels: Topic: Catalysis, Twin RMG-database PR

#2175 Update documentation to reflect additions in RMG-database
  arkane/encorr/bac.py
  arkane/encorr/bacTest.py
  documentation/source/users/arkane/input.rst
Labels: Arkane, Complexity: Low, Type: Documentation
